#!/bin/sh
# embed_shaders.sh — turn src/shaders/*.vert|.frag into a C header of string
# literals.
#
# Shaders are embedded rather than read from disk at runtime for two reasons
# that both come from the target: the Zero 2W boots from microSD with slow
# random I/O (PLAN.md §1), and the deployment story is "a single ELF launched
# from a TTY" (§2) — a binary that needs a sibling directory of .glsl files is
# not that.
#
# usage: embed_shaders.sh OUT_HEADER SHADER_DIR
set -eu

out=$1
dir=$2

tmp="$out.tmp$$"
trap 'rm -f "$tmp"' EXIT

{
    echo "/* Generated by tools/embed/embed_shaders.sh — do not edit. */"
    echo "#ifndef TP_SHADERS_GENERATED_H"
    echo "#define TP_SHADERS_GENERATED_H"
    echo
} > "$tmp"

for f in "$dir"/*.vert "$dir"/*.frag; do
    [ -e "$f" ] || continue

    base=$(basename "$f")
    # character.vert -> tp_shader_character_vert
    # printf, not echo: echo's trailing newline would become an underscore.
    sym="tp_shader_$(printf '%s' "$base" | tr -c 'A-Za-z0-9' '_')"

    echo "static const char $sym[] =" >> "$tmp"

    # Escape backslashes and double quotes, then wrap each line as a literal.
    # Comments are kept: they end up in the driver's shader log, which is
    # exactly where you want them when Panfrost rejects something.
    sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$/\\n"/' "$f" >> "$tmp"

    echo ";" >> "$tmp"
    echo >> "$tmp"
done

{
    echo "#endif /* TP_SHADERS_GENERATED_H */"
} >> "$tmp"

mv "$tmp" "$out"
trap - EXIT
